export  const codes = [
    { code: "IST", city: "İstanbul", airportName: "İstanbul Havalimanı" },
    { code: "ISL", city: "İstanbul", airportName: "Atatürk Havalimanı" },
    { code: "SAW", city: "İstanbul", airportName: "Sabıha Gökçen Uluslararası Havalimanı" },
    { code: "ADB", city: "İzmir", airportName: "Adnan Menderes Havalimanı" },
    { code: "AYT", city: "Antalya", airportName: "Antalya Havalimanı" },
    { code: "BJV", city: "Bodrum", airportName: "Milas–Bodrum Havalimanı" },
    { code: "DLM", city: "Dalaman", airportName: "Dalaman Havalimanı" },
    { code: "ESB", city: "Ankara", airportName: "Ankara Esenboğa Havalimanı" },
    { code: "ASR", city: "Kayseri", airportName: "Kayseri Erkilet Havalimanı" },
    { code: "GZT", city: "Gaziantep", airportName: "Oğuzeli Havalimanı" },
    { code: "HTY", city: "Hatay", airportName: "Hatay Havalimanı" },
    { code: "DIY", city: "Diyarbakır", airportName: "Diyarbakır Havalimanı" },
    { code: "SZF", city: "Samsun", airportName: "Samsun-Çarşamba Havalimanı" },
    { code: "TZX", city: "Trabzon", airportName: "Trabzon Havalimanı" },
    { code: "VAS", city: "Sivas", airportName: "Sivas Nuri Demirağ Havalimanı" },
    { code: "DNZ", city: "Denizli", airportName: "Denizli Çardak Havalimanı" },
    { code: "ERZ", city: "Erzurum", airportName: "Erzurum Havalimanı" },
    { code: "BAL", city: "Batman", airportName: "Batman Havalimanı" },
    { code: "AJI", city: "Ağrı", airportName: "Ağrı Havalimanı" },
    { code: "CKZ", city: "Çanakkale", airportName: "Çanakkale Havalimanı" },
    { code: "EZS", city: "Elazığ", airportName: "Elazığ Havalimanı" },
    { code: "KSY", city: "Kars", airportName: "Kars Harakani Havalimanı" },
    { code: "KCM", city: "Kahramanmaraş", airportName: "Kahramanmaraş Havalimanı" },
    { code: "KYA", city: "Konya", airportName: "Konya Havalimanı" },
    { code: "MLX", city: "Malatya", airportName: "Malatya Erhaç Havalimanı" },
    { code: "Zonguldak", city: "ONQ", airportName: "Zonguldak Havalimanı" },
    { code: "IGD", city: "Iğdır", airportName: "Iğdır Havalimanı" },
    { code: "HTY", city: "Hatay", airportName: "Hatay Havalimanı" },
    { code: "EZS", city: "Elazığ", airportName: "Elazığ Havalimanı" },
    { code: "GZT", city: "Gaziantep", airportName: "Oğuzeli Havalimanı" },
    { code: "KYA", city: "Konya", airportName: "Konya Havalimanı" },
    { code: "MLX", city: "Malatya", airportName: "Malatya Erhaç Havalimanı" },
    { code: "SZF", city: "Samsun", airportName: "Samsun-Çarşamba Havalimanı" },
    { code: "VAS", city: "Sivas", airportName: "Sivas Nuri Demirağ Havalimanı" },
    { code: "DNZ", city: "Denizli", airportName: "Denizli Çardak Havalimanı" },
    { code: "KCM", city: "Kahramanmaraş", airportName: "Kahramanmaraş Havalimanı" },
    { code: "ASR", city: "Kayseri", airportName: "Kayseri Erkilet Havalimanı" },
    { code: "AJI", city: "Ağrı", airportName: "Ağrı Havalimanı" },
    { code: "BAL", city: "Batman", airportName: "Batman Havalimanı" },
    { code: "CKZ", city: "Çanakkale", airportName: "Çanakkale Havalimanı" },
    { code: "DIY", city: "Diyarbakır", airportName: "Diyarbakır Havalimanı" },
    { code: "ERZ", city: "Erzurum", airportName: "Erzurum Havalimanı" },
    { code: "KSY", city: "Kars", airportName: "Kars Harakani Havalimanı" },
    { code: "TZX", city: "Trabzon", airportName: "Trabzon Havalimanı" },
    { code: "Zonguldak", city: "ONQ", airportName: "Zonguldak Havalimanı" },
    { code: "ECN", city: "Ercan", airportName: "Ercan Uluslararası Havalimanı" },
    { code: "GZP", city: "Alanya", airportName: "Alanya Gazipaşa Havalimanı" },
    { code: "USQ", city: "Uşak", airportName: "Uşak Havalimanı" },
    { code: "ADA", city: "Adana", airportName: "Adana Havalimanı" },
    { code: "SZF", city: "Samsun", airportName: "Samsun-Çarşamba Havalimanı" },
    { code: "ISE", city: "Isparta", airportName: "Süleyman Demirel Havalimanı" },
    { code: "CKZ", city: "Çanakkale", airportName: "Çanakkale Havalimanı" },
    { code: "IZM", city: "İzmir", airportName: "İzmir Adnan Menderes Havalimanı" }
];